package uci

var IsReady = NewCommand("isready").EnsureNewLine()
var ReadyOk = NewCommand("readyok")
var Uci = NewCommand("uci").EnsureNewLine()
var UciOk = NewCommand("uciok")
var UciNewGame = NewCommand("ucinewgame").EnsureNewLine()
var Stop = NewCommand("stop").EnsureNewLine()
var Go = NewCommand("go")
var Position = NewCommand("position")
var SetOption = NewCommand("setoption")
var DebugOn = NewCommand("debug").WithFlag("on").EnsureNewLine()
var DebugOff = NewCommand("debug").WithFlag("off").EnsureNewLine()
var Register = NewCommand("register")
var RegisterLater = Register.WithFlag("later").EnsureNewLine()
var PonderHit = NewCommand("ponderhit").EnsureNewLine()
var Quit = NewCommand("quit").EnsureNewLine()
var Id = NewCommand("id")
var Option = NewCommand("option")
var Stockfish = NewCommand("Stockfish")
